import {cpt} from './cpt-data.mjs';
import {cft} from './cft-data.mjs';
import {nutrition} from './nutrition-data.mjs';
import {cupping} from './cupping-data.mjs';
import {massage} from './massage-data.mjs';
import {chiropractic} from './chiropractic-data.mjs';

export function renderCourses({esc,img,link,button,arrow,star}) {
 const programs=[
  [cpt,'training','التدريب الشخصي','CPT','14 يومًا','10 أيام نظري + 4 أيام عملي','3,000','التشريح والحركة · تصميم البرامج · التدريب داخل الجيم'],
  [cft,'training','اللياقة والإعداد البدني','CFT','13 يومًا','10 أيام نظري + 3 أيام عملي','3,000','عناصر اللياقة · الاختبارات والقياسات · إعداد الرياضيين'],
  [nutrition,'nutrition','التغذية الرياضية','NUTRITION','4 أيام','محاضرات نظرية','800','فسيولوجيا التغذية · التمثيل الغذائي · تخطيط الأنظمة'],
  [cupping,'recovery','الحجامة وكاسات الهواء','CUPPING','5 أيام','90% من الساعات عملي','1,000','الحجامة · كاسات الهواء · التدليك بالكاسات'],
  [massage,'recovery','التدليك والحمام المغربي','MASSAGE','5 أيام','90% من الساعات عملي','900','التدليك الرياضي والعلاجي والاسترخائي · الحمام المغربي'],
  [chiropractic,'recovery','الكيروبراكتيك والتاي مساج','MOVEMENT','5 أيام','90% من الساعات عملي','800','الكيروبراكتيك · التدليك التايلاندي · التطبيقات التعليمية']
 ];
 const href=d=>'course-'+(d.slug||d.abbreviation.toLowerCase())+'.html';
 return `<div class="courses-experience"><section class="container academy-opening"><div class="academy-intro"><a class="breadcrumb" href="index.html">الرئيسية / الكورسات</a><span class="eyebrow">DR. ALI NOUR / EDUCATION</span><h1>معرفة تُلهمك.<br><span>ومهارة تُحرّكك.</span></h1><p>خطوتك القادمة تبدأ بالتعلّم. اكتشف برامج التدريب واللياقة والتغذية والاستشفاء، واختر المجال الذي يناسب هدفك.</p><div class="academy-actions">${button('اكتشف البرامج','#programs')}${link('قارن بين البرامج','#compare')}</div><div class="academy-location"><span class="academy-dot"></span>أسيوط، مصر <span>حضوري · خيار أونلاين وفق الإعلان</span></div></div><aside class="academy-paths"><div class="academy-paths-top"><span lang="en" dir="ltr">FIND YOUR DIRECTION</span><span aria-hidden="true">${star}</span></div><h2>لكل شغف،<br> مسار تتعلّمه.</h2><div class="academy-path-row"><span>01</span><div><strong>التدريب واللياقة</strong><small>من التدريب الشخصي إلى إعداد الرياضيين</small></div><span lang="en">CPT / CFT</span></div><div class="academy-path-row"><span>02</span><div><strong>التغذية الرياضية</strong><small>افهم العلاقة بين الغذاء والأداء</small></div><span lang="en">NUTRITION</span></div><div class="academy-path-row"><span>03</span><div><strong>الاستشفاء والعناية بالجسم</strong><small>استكشف مجالات التدليك والممارسات اليدوية</small></div><span lang="en">RECOVERY</span></div><div class="academy-paths-foot"><strong>06</strong><span>برامج تعليمية<br>بمحتوى تفصيلي</span><span lang="en" dir="ltr">SCIENCE IN MOTION ↗</span></div></aside></section>
 <section id="programs" class="container academy-programs"><div class="academy-catalogue-heading"><div><span class="eyebrow">اختر خطوتك القادمة</span><h2>برامج تستحق الاكتشاف<span>.</span></h2></div><p>تعرّف على المحتوى ونظام الدراسة والمحاضرين<br>قبل اختيار البرنامج المناسب لك.</p></div><div class="course-toolbar"><div class="filter-group" role="group" aria-label="تصفية الكورسات حسب المجال">${[['all','كل البرامج','06'],['training','التدريب واللياقة','02'],['nutrition','التغذية','01'],['recovery','الاستشفاء والتدليك','03']].map(([id,t,n])=>`<button class="filter-button${id==='all'?' active':''}" data-filter="${id}" aria-pressed="${id==='all'}">${t} <span>${n}</span></button>`).join('')}</div><label class="course-search"><span aria-hidden="true">⌕</span><input type="search" id="course-search" placeholder="ابحث عن برنامج…" aria-label="ابحث باسم الكورس أو المحاضر"></label></div><div class="academy-result-line"><p class="course-result" role="status" aria-live="polite">عرض 6 كورسات</p><span>تعلّم العلم. وابدأ التطبيق.</span></div><div class="course-grid course-list academy-course-grid">${programs.map(([d,category,title,code,days,mode,price,topics],i)=>`<article class="course-card academy-card" data-category="${category}" data-search="${esc([d.name,d.englishName,code,title,topics,'د. علي نور',...(d.lecturers||[]).map(x=>x[0])].join(' '))}"><a class="academy-card-image" href="${href(d)}" aria-label="اكتشف ${esc(title)}">${img(d.editorial.poster,'صورة برنامج '+title)}<span class="academy-card-arrow" aria-hidden="true">${arrow}</span></a><div class="academy-card-content"><div class="academy-card-kicker"><span>${category==='training'?'التدريب واللياقة':category==='nutrition'?'التغذية الرياضية':'الاستشفاء والعناية'}</span><span lang="en" dir="ltr">${code} / ${String(i+1).padStart(2,'0')}</span></div><h3><a href="${href(d)}">${esc(title)}</a></h3><p class="academy-card-topics">${esc(topics)}</p><div class="academy-card-study"><strong>${days}</strong><span>${mode}</span></div><div class="academy-card-bottom"><div><small>الرسوم المعلنة</small><strong dir="rtl"><b dir="ltr">${price}</b> <span>جنيه</span></strong></div>${link('تفاصيل البرنامج',href(d))}</div></div></article>`).join('')}</div><div class="empty-state" hidden><h3>لم نجد برنامجًا بهذا البحث.</h3><p>جرّب كلمة مختلفة أو اعرض كل البرامج.</p><button class="button button-dark" id="reset-filters" type="button">عرض كل البرامج ${arrow}</button></div><p class="academy-price-note">الأسعار وفق الإعلانات المقدمة، وتُؤكد الأسعار السارية ومواعيد الدفعات وتوافر الأماكن مع الإدارة قبل التسجيل.</p></section>
 <section id="compare" class="container academy-comparison"><div class="academy-catalogue-heading"><div><span class="eyebrow">الصورة الكاملة، ببساطة</span><h2>أي برنامج يناسبك؟</h2></div><p>قارن المدة وطبيعة الدراسة والرسوم المعلنة.</p></div><div class="academy-table-wrap" tabindex="0" role="region" aria-label="جدول مقارنة البرامج، قابل للتمرير أفقيًا"><table><caption class="academy-table-caption">مقارنة البرامج التعليمية الستة</caption><thead><tr><th scope="col">البرنامج</th><th scope="col">المدة</th><th scope="col">نظام الدراسة</th><th scope="col">الرسوم المعلنة</th></tr></thead><tbody>${programs.map(([d,cat,title,code,days,mode,price])=>`<tr><th scope="row"><a href="${href(d)}">${title} <span aria-hidden="true">↗</span></a></th><td>${days}</td><td>${mode}</td><td><span dir="ltr">${price}</span> جنيه</td></tr>`).join('')}</tbody></table></div><p class="academy-price-note">تُراجع آلية التدريب العملي وخيارات الدراسة أونلاين والشهادات وشروط القبول في صفحة كل برنامج وعند التسجيل.</p></section>
 <section class="container academy-help"><span class="eyebrow">نساعدك تختار</span><h2>هدفك واضح.<br>تحتاج فقط إلى الخطوة الأولى.</h2><p>تواصل للاستفسار عن البرنامج المناسب، شروط الالتحاق، وموعد الدفعة القادمة.</p>${button('استفسر عن البرامج','https://wa.me/201091923434','lime')}<span class="academy-help-star" aria-hidden="true">${star}</span></section></div>`;
}
